# luci-theme-ppip
#
# ppiptheme is an alternative HTML5 theme for LuCI that has evolved from
# luci-theme-bootstrap & luci-theme-material, in an attempt to bring a more
# concise, clean and visually pleasing UX to LEDE/OpenWRT.
# 
# Copyright 2020 LeoHao <blueseamyheart@hotmail.com>
# 
include $(TOPDIR)/rules.mk

LUCI_TITLE:=PPIP Theme
LUCI_DEPENDS:=

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
